// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/alumnos': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/alumnos.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/alumnos.post').default>>>>
    }
    '/api/alumnos/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/alumnos/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/alumnos/[id].put').default>>>>
    }
    '/api/asistencias': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/asistencias.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/asistencias.post').default>>>>
    }
    '/api/estadisticas': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/estadisticas.get').default>>>>
    }
    '/api/grupos': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/grupos.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/grupos.post').default>>>>
    }
    '/api/grupos/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/grupos/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/grupos/[id].put').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}